# Generated by Django 3.2.13 on 2022-07-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_createcurrency_currencyalter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Null', max_length=225)),
                ('alias', models.CharField(blank=True, default='Null', max_length=225)),
                ('under', models.CharField(blank=True, default='Null', max_length=225)),
                ('nature_of_group', models.CharField(blank=True, default='Null', max_length=225)),
                ('does_it_affect', models.CharField(blank=True, default='Null', max_length=225)),
                ('gp_behaves_like_sub_ledger', models.CharField(blank=True, default='Null', max_length=225)),
                ('nett_debit_credit_bal_reporting', models.CharField(blank=True, default='Null', max_length=225)),
                ('used_for_calculation', models.CharField(blank=True, default='Null', max_length=225)),
                ('method_to_allocate_usd_purchase', models.CharField(blank=True, default='Null', max_length=225)),
            ],
        ),
    ]
