# Generated by Django 3.2.13 on 2022-07-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_groupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledgerModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('ledger_type', models.CharField(max_length=225)),
                ('mailling_name', models.CharField(max_length=225)),
                ('mailling_address', models.CharField(max_length=225)),
                ('mailling_country', models.CharField(max_length=225)),
                ('mailling_state', models.CharField(max_length=225)),
                ('mailling_pincode', models.CharField(max_length=225)),
                ('bank_details', models.CharField(default='Null', max_length=225)),
                ('pan_number', models.CharField(max_length=225)),
                ('registration_type', models.CharField(max_length=225)),
                ('gst_number', models.CharField(max_length=225)),
                ('alter_gst_details', models.CharField(max_length=225)),
            ],
        ),
    ]
