# Generated by Django 3.2.13 on 2022-07-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_ledgermodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgermodels',
            old_name='voucher_name',
            new_name='ledger_name',
        ),
    ]
