# Generated by Django 3.2.13 on 2022-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_rename_voucher_name_ledgermodels_ledger_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgermodels',
            old_name='alter_gst_details',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='ledgermodels',
            old_name='gst_number',
            new_name='active_this_voucher_type',
        ),
        migrations.RenameField(
            model_name='ledgermodels',
            old_name='mailling_address',
            new_name='allow_naration_in_voucher',
        ),
        migrations.RenameField(
            model_name='ledgermodels',
            old_name='mailling_country',
            new_name='allow_zero_value_trns',
        ),
        migrations.RenameField(
            model_name='ledgermodels',
            old_name='mailling_name',
            new_name='make_optional',
        ),
        migrations.RenameField(
            model_name='ledgermodels',
            old_name='mailling_pincode',
            new_name='method_voucher_numbering',
        ),
        migrations.RenameField(
            model_name='ledgermodels',
            old_name='mailling_state',
            new_name='print_voucher',
        ),
        migrations.RenameField(
            model_name='ledgermodels',
            old_name='pan_number',
            new_name='provide_naration',
        ),
        migrations.RenameField(
            model_name='ledgermodels',
            old_name='bank_details',
            new_name='use_effective_date',
        ),
        migrations.RemoveField(
            model_name='ledgermodels',
            name='registration_type',
        ),
        migrations.AddField(
            model_name='ledgermodels',
            name='prvnt_duplictes',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='ledgermodels',
            name='use_adv_conf',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
