# Generated by Django 3.2.13 on 2022-07-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_auto_20220715_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgermodels',
            name='print_voucher',
        ),
    ]
