# Generated by Django 3.2.13 on 2022-07-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_remove_ledgermodels_print_voucher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ledgerModels',
        ),
    ]
