# Generated by Django 4.2.29 on 2026-03-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_rename_maiil_name_ledgermodels_mail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=225, unique=True)),
                ('value', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_names', models.TextField(default='')),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.CharField(default='0 KB', max_length=50)),
                ('backup_format', models.CharField(default='zip', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_format', models.CharField(default='excel', max_length=50)),
                ('destination_folder', models.CharField(default='', max_length=500)),
                ('open_after_export', models.CharField(default='yes', max_length=10)),
                ('include_logo', models.CharField(default='yes', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_format', models.CharField(default='xml', max_length=50)),
                ('default_master_type', models.CharField(default='ledgers', max_length=50)),
                ('duplicate_handling', models.CharField(default='ignore', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('file_format', models.CharField(default='csv', max_length=50)),
                ('master_type', models.CharField(default='ledgers', max_length=50)),
                ('field_mappings', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(default='Microsoft Print to PDF', max_length=225)),
                ('paper_size', models.CharField(default='a4', max_length=50)),
                ('orientation', models.CharField(default='portrait', max_length=50)),
                ('print_preview', models.CharField(default='yes', max_length=10)),
                ('copy_marking', models.CharField(default='none', max_length=50)),
                ('num_copies', models.IntegerField(default=1)),
                ('show_company_name', models.CharField(default='yes', max_length=10)),
                ('show_company_address', models.CharField(default='no', max_length=10)),
                ('show_company_logo', models.CharField(default='no', max_length=10)),
                ('report_title', models.CharField(blank=True, default='Auto (from report)', max_length=225)),
                ('report_subtitle', models.CharField(blank=True, default='', max_length=225)),
                ('margin_top', models.IntegerField(default=10)),
                ('margin_bottom', models.IntegerField(default=10)),
                ('margin_left', models.IntegerField(default=15)),
                ('margin_right', models.IntegerField(default=15)),
            ],
        ),
    ]
