# Generated by Django 4.2.29 on 2026-03-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_appsetting_backuplog_exportconfig_importconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crtcompony',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='booksbgn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=50),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='crncyname',
            field=models.CharField(blank=True, default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='curncysymbl',
            field=models.CharField(blank=True, default='₹', max_length=10),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='fyearbgn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='mailingname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='telphone',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='crtcompony',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
