# Generated by Django 4.2.29 on 2026-03-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_alter_crtcompony_address_alter_crtcompony_booksbgn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_type', models.CharField(max_length=100)),
                ('voucher_number', models.IntegerField()),
                ('narration', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.crtcompony')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.ledgermodels')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='App1.transaction')),
            ],
        ),
    ]
